apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: heapster
    name: heapster
    kubernetes.io/minikube-addons: heapster
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: heapster
  template:
    metadata:
      labels:
        addonmanager.kubernetes.io/mode: Reconcile
        k8s-app: heapster
    spec:
      containers:
      - name: heapster
        image: registry.cn-hangzhou.aliyuncs.com/google_containers/heapster:v1.4.3
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes
        - --sink=influxdb:http://monitoring-influxdb:8086
        - --metric_resolution=60s
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/ssl/certs
          readOnly: true
      volumes:
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
